### PR TITLE
feat: add navigation for sections of dashboard

### LINKED ISSUE #8: Subdivide dashboard into sections / add navigation sidebar
**Note: If you get approved for this bounty, join the [DITTO Telegram group](https://t.me/dittomoney) and ping @chefchansey for more details.**

Subdivide the [DITTO dashboard](https://ditto.money/dashboard/) into three sections:

- Price and supply statistics
- Trading volume
- Rebase history

Also, add a sidebar for navigating between the sections. See [here](https://www.ampleforth.org/dashboard/) for inspiration.

### PR DESCRIPTION
**Pull request by brymut**
Resolve #8: Added sidebar navigation for the three sections of the dashboard

https://user-images.githubusercontent.com/14836056/107170669-06056e80-69d2-11eb-9d22-d4fff4c15770.mov

Hi, @chefchansey @vbstreetz please have a look when you can.

### CODE REVIEW

**Comment by kelonye** [comment]
Hapo sawa 🙂. Maybe utilize https://material-ui.com/components/drawers/ ?

**Comment by kelonye** [comment]
Also. I'd use the router as the nav state manager. So basically would cool to visit the sections via the location bar/, /#/volumes, etc

**Comment by brymut** [comment]
@vbstreetz could you please check it again when you can? Now using a drawer for the small viewport and router to manage state of sections shown.

**Comment by kelonye** [comment]
Sure. Checking..

**Comment by kelonye** [comment]
Hey. Nice progress. So I was thinking something like what's at https://pancakeswap.finance/ i.e. https://material-ui.com/components/drawers/#permanent-drawer

**Comment by kelonye** [comment]
Btw, for some reason it doesn't show on larger screens...

Screenshot 2021-02-08 at 20 02 56
Screenshot 2021-02-08 at 20 02 44

**Comment by kelonye** [comment]
> Hey. Nice progress. So I was thinking something like what's at https://pancakeswap.finance/ i.e. https://material-ui.com/components/drawers/#permanent-drawer

Can pick some icons from https://material-ui.com/components/material-icons/#material-icons

**Comment by brymut** [comment]
> Hey. Nice progress. So I was thinking something like what's at https://pancakeswap.finance/ i.e. https://material-ui.com/components/drawers/#permanent-drawer

Could you please be more specific about what you would like changed? Switching around is making it that I have to redo quite a bit. Also, which icons would you like me to use?

**Comment by brymut** [comment]
> Btw, for some reason it doesn't show on larger screens...
> 
> 
> 
> Screenshot 2021-02-08 at 20 02 56
> 
> Screenshot 2021-02-08 at 20 02 44
> 
> 

What isn't showing?

**Comment by brymut** [comment]
Do you mean the drawer? I figured we don't need it since everything will fit in fine without a drawer. But I can add in the permanent drawer for the larger viewport if that's what you prefer.

**Comment by kelonye** [comment]
Gotcha. Sorry I'm a bit of a UI nit-pick so just thought we'd try a few different options. I think I'll let @chefchansey  pick up from hear since I've limited time left.

**Comment by brymut** [comment]
> Gotcha. Sorry I'm a bit of a UI nit-pick so just thought we'd try a few different options. I think I'll let @chefchansey pick up from hear since I've limited time left.

Could you please clarify what you meant first?

**Comment by brymut** [comment]
Applied some changes to fix the margin. 
Screenshot 2021-02-10 at 12 18 32
Screenshot 2021-02-10 at 12 18 22

**Comment by chefchansey** [comment]
The menu looks great IMO! I have a few of change requests:

1. Change "Price and supply statistics" to just "Price and supply"
2. Move content from "Trading volume" to "Price and supply statistics" (both tiles and charts should be on the same page)
3. Remove "Trading volume" menu item (just comment it out for now - the volume data [still needs to be added](https://github.com/Ditto-money/dashboard/issues/3))

Thanks @brymut!

**Comment by chefchansey** [comment]
Also rebase history is empty for me... not sure if that's because I'm running it locally?

**Comment by brymut** [comment]
> Also rebase history is empty for me... not sure if that's because I'm running it locally?

Same for me too, its the local dev environment needs some config. Maybe @vbstreetz can clarify?

**Comment by brymut** [comment]
> The menu looks great IMO! I have a few of change requests:
> 
> 1. Change "Price and supply statistics" to just "Price and supply"
> 2. Move content from "Trading volume" to "Price and supply statistics" (both tiles and charts should be on the same page)
> 3. Remove "Trading volume" menu item (just comment it out for now - the volume data [still needs to be added](https://github.com/Ditto-money/dashboard/issues/3))
> 
> Thanks @brymut!

I've applied your requested changes.

**Comment by kelonye** [comment]
> > Also rebase history is empty for me... not sure if that's because I'm running it locally?
> 
> Same for me too, its the local dev environment needs some config. Maybe @vbstreetz can clarify?

Hey. Pushed a fix here https://github.com/Ditto-money/dashboard/commit/0cae9970c1900b7589c9b02794a2113866590f93. Should now be able to add this in your .env:

```
REACT_APP_API_URL=https://ditto.money/api
```

**Pull request merged**
